### ISSUE TITLE
Annoying when you are editing functions.

### ISSUE THREAD

**Issue by henrikvik** [beldar/Auto-Brackets#2]
I love this plugin but I hate it at the same time. Its great when you are creating functions but it creates a new bracket when I try to make new lines at the top of the function since I place my cursor at the end of the first line where there is an opening bracket. 

Please make it smart enough to not create excess brackets.

**Comment by beldar** [comment]
@Henk-e i know exactly what you mean, how would you fix it?
Maybe when there's something else on the line below don't execute the change?

**Comment by henrikvik** [comment]
@beldar That would be a good start. I was thinking about if the problem could be solved with indexOf() and push in starting brackets and pop out them if it gets a closing bracket. but I didn't get anywhere. Maybe you cold give it a shot.

**Comment by iuliangcata** [comment]
:+1:  +1 to this problem .

**Comment by Slayvin** [comment]
Same thought for me: I love this feature, but that small issue makes it really annoying at the same time!
There is also that case when I see this issue:
When you place your cursor at the beginning of any line that is ending with '{', '(' or '[' and press Enter to create a new line, it will add an undesired closing bracket since the last character of the line is an opening bracket...
To fix this, I would suggest to check the position of the cursor when pressing Enter: it should be positioned **after** the brackets to work.

**Comment by iuliangcata** [comment]
One other strange behaviour I get on the css files, when I have a definition and place my cursor in front of it and then press enter to make room for another declaration, I get a } in front of it, like:

.class{}; -> }.class{};

**Comment by beldar** [comment]
Hi all,

I was determined to fix this today, I downloaded the latest version of Brackets (0.42 at this moment), and read through the documentation (because it would've probably changed) when I found this method from the editor [Editor.getCloseBrackets](http://brackets.io/docs/current/modules/editor/Editor.html#Editor-getCloseBrackets) that reads:

_Gets whether the specified or current file uses auto close brackets_

So basically I discovered that Brackets does what this extension intended to do out of the box now, to activate it, open the preference file `Debug -> Open Preferences File` and add this line:

```
"closeBrackets": true
```

And Cmd+R to reload the editor, now Brackets will close all your brackets (no pun intended) and ultimately doing what this extension was supposed to do way better than it currently does it.

So without further a due I declare this extension deprecated and I advise you use the native method.

Thank you all for your interest.

**Comment by Slayvin** [comment]
Thanks, but still not working for me. I updated to 0.42 but the fix you suggested has no effect...
I think it's related to this bug (I'm using a French (non-US) keyboard) : https://github.com/adobe/brackets/issues/8271
I'll wait for 0.43 I guess !

**Comment by le717** [comment]
@beldar Not directly related to this issue, but just wanted to say the auto close braces feature has been in Brackets much longer than 0.42. IIRC, it was present somewhere in Sprint late-30s when I started using Brackets. The feature can also be enabled/disabled though the Edit>Auto Close Braces menu item. :)

**Comment by iuliangcata** [comment]
@beldar This has never worked for me, a bit strange behaviour.
